version: "3.9"  
  
services:  
  fastapi_service:  
    build:  
      context: ./  
      dockerfile: Dockerfile  
    hostname: fastapi_service  
    container_name: fastapi_service  
    depends_on:  
      - db_postgres  
    ports:  
      - "8000:8000"  
    env_file:  
      - .env  
    volumes:  
      - ./:/home/app  
    networks:  
      - my-net  
    command: 
     [
      "poetry",
      "run",
      "uvicorn",
      "--host",
      "0.0.0.0",
      "--port",
      "8000",
      "app.main:app",
      "--reload",
      ]
  
  db_postgres:  
    image: postgres:15.3-alpine  
    hostname: db_postgres  
    container_name: ${PG_CONTAINER_NAME}  
    restart: always
    environment:  
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:  
      - "${DATABASE_PORT}:5432"  
    env_file:
      - ./.env
    volumes:  
      - ./db-postgres:/var/lib/postgresql/data  
    networks:  
      - my-net  
  
networks:  
  my-net: